### ISSUE TITLE
Error: Use of unresolved identifier 'DecodeData'

### ISSUE THREAD

**Issue by Error-freeIT** [FitnessKit/DataDecoder#1]
Hi Kevin,

To rule out anything else I have created a new iOS Project (Single View App), installed DataDecoder via CocoaPods. My Podfile contains the following:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynam$
  use_frameworks!

  # Pods for Example
  pod "DataDecoder"
end
```

Ran pod install and opened the new workspace (Example.xcworkspace).

I import DataDecoder at the top of my ViewController and paste the example code into viewDidLoad. This gives me the compiler error: Use of unresolved identifier 'DecodeData'.

<img width="823" alt="xcode error" src="https://user-images.githubusercontent.com/5794097/49485062-46fd1800-f889-11e8-9fc2-6c1a3fed91fe.png">

Can you see why that would be happening?

Thank you
Michael

**Comment by khoogheem** [comment]
Michael -

Sorry for not getting back to you.  I just created a new Xcode project and am not seeing the same issue.

Let me know if you have figured it out or not
